# Generated by Django 3.2 on 2021-04-10 08:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_create_superuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homemodel",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
