name: Django tests

on: [pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: shops_parser_db
          POSTGRES_USER: shops_parser_user
          POSTGRES_PASSWORD: shops_parser_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install V
      run: pip install virtualenv

    - name: Create virtualenv
      run: virtualenv venv

    - name: Activate virtualenv
      run: source venv/bin/activate

    - name: Install poetry
      run: pip install -U pip setuptools poetry

    - name: Install Dependencies
      run: |
        cd src/
        poetry install

    - name: Install Django
      run: pip install Django

    - name: Run Tests
      run: python src/manage.py test
      env:
        POSTGRES_DB: shops_parser_db
        POSTGRES_USER: shops_parser_user
        POSTGRES_PASSWORD: shops_parser_password