name: Django tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: parser-admin
          POSTGRES_PASSWORD: parser-password
          POSTGRES_DB: parser-db
        ports: ['5432:5432']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Check postgres
      run: psql --version

    - name: Install poetry
      run: pip install -U pip setuptools poetry

    - name: Install Dependencies
      run: |
        cd src/
        poetry install

    - name: Run Tests
      run: python src/manage.py test
      env:
        DB: parser-db
        DB_USER: parser-admin
        DB_PASSWORD: parser-password