name: Django tests

on: [pull_request]

jobs:
  tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: shops_parser_db
          POSTGRES_USER: shops_parser_user
          POSTGRES_PASSWORD: shops_parser_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: install library
      run: |
        cd src/
        pip install requirements.txt

    - name: Run Tests
      run: python src/manage.py test

      env:
        POSTGRES_DB: shops_parser_db
        POSTGRES_USER: shops_parser_user
        POSTGRES_PASSWORD: shops_parser_password