name: Django tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: parser-admin
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: parser-password
        ports: [ '5432:5432' ]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Check postgres
      run: postgres --version

    - name: Install poetry
      run: pip install -U pip setuptools poetry

    - name: Install Dependencies
      run: |
        cd src/
        poetry install

#    - name: Run Tests
#      run: python src/manage.py test
#      env:
#        DB: ${{ matrix.db }}
#        DB_USER: ${{ matrix.db_user }}
#        DB_PASSWORD: ${{ matrix.db_password }}